package com.udacity.course3.reviews.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.udacity.course3.reviews.entity.Review;

public interface ReviewRepository extends JpaRepository<Review, Integer> {

	/*
	 * Finds all the reviews based on the productId.
	 * Generated by JPA at runtime
	 * 
	 * @param : Integer product id to do the search
	 * @result: List of reviews have product id same as @param
	 */
	List<Review> findByProductId(Integer productId);
	
	
	/*
	 * Fetch the list of review ID's based on the product ID
	 * 
	 * @param : Integer product id to do the search
	 * @result: List of Integer containing review id's having product id as @param
	 */
	@Query("select r.id from Review r where r.product.id=:productId")
	List<Integer> findReviewIdsByProductId(@Param("productId") Integer productId);

}
